name: Test Quality Analysis
description: Analyze the quality of your test files with AI
author: Aetherr-Agency

branding:
  icon: check-circle
  color: purple

inputs:
  openai_api_key:
    description: Your OpenAI API key
    required: true
  github_token:
    description: Your GitHub token
    required: false
  batch_size:
    description: The number of files to process in each batch
    required: false
    default: "5"
  model:
    description: The model to use for the test files
    required: false
    default: "gpt-4o-mini"
  temperature:
    description: The temperature to use for the test files
    required: false
    default: "0.5"
  test_files:
    description: Whitespaces separated list of glob patterns to find test files
    required: false
    default: "**/*.test.ts"
  only_changed_files:
    description: Only analyze test files that have been changed in the PR
    required: false
    default: "true"

outputs:
  summary:
    description: The summary of the test files
  detailed_report:
    description: The detailed report of the test files
  markdown_comment:
    description: The markdown comment to post to the PR

runs:
  using: docker
  image: Dockerfile
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    BATCH_SIZE: ${{ inputs.batch_size }}
    MODEL: ${{ inputs.model }}
    TEMPERATURE: ${{ inputs.temperature }}
    TEST_FILES: ${{ inputs.test_files }}
    ONLY_CHANGED_FILES: ${{ inputs.only_changed_files }}
