name: Test Quality Analysis
description: Analyze the quality of your test files with AI
author: Aetherr-Agency

branding:
  icon: check-circle
  color: purple

inputs:
  openai_api_key:
    description: Your OpenAI API key
    required: true
  github_token:
    description: Your GitHub token
    required: false
  batch_size:
    description: The number of files to process in each batch
    required: false
    default: "5"
  model:
    description: The model to use for the test files
    required: false
    default: "gpt-4o-mini"
  temperature:
    description: The temperature to use for the test files
    required: false
    default: "0.5"
  test_files:
    description: Whitespaces separated list of glob patterns to find test files
    required: false
    default: "**/*.test.ts"

outputs:
  summary:
    description: The summary of the test files
  detailed_report:
    description: The detailed report of the test files
  markdown_comment:
    description: The markdown comment to post to the PR

runs:
  using: node20
  main: dist/index.js
